# Generated by Django 3.2.4 on 2021-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userlist',
            fields=[
                ('user_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('user_DOB', models.DateField()),
            ],
        ),
    ]
