# Generated by Django 3.2.4 on 2021-06-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
