# Generated by Django 3.2.4 on 2021-06-30 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Database_Management', '0002_alter_userlist_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='user_pwd',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
