# Generated by Django 3.2.4 on 2021-07-03 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Database_Management', '0003_userlist_user_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='File_to_be_uploaded',
            field=models.FileField(default=django.utils.timezone.now, upload_to='Cars_JPG'),
            preserve_default=False,
        ),
    ]
